#!/usr/bin/env python3
"""Verify target archives without extraction (including case-sensitive Linux runtime files)."""
import argparse
import ast
import hashlib
import json
import struct
import zipfile
from pathlib import Path
from native_packaging import CONFIG, LOADER, wrapper


def architecture(data):
    if data[:4] == b'\x7fELF':
        return {62:'x86_64',183:'arm64'}.get(struct.unpack_from('<H',data,18)[0])
    if data[:4] == b'\xcf\xfa\xed\xfe':
        return {0x01000007:'x86_64',0x0100000c:'arm64'}.get(struct.unpack_from('<I',data,4)[0])
    if data[:2] == b'MZ':
        offset=struct.unpack_from('<I',data,0x3c)[0]
        return {0x8664:'x86_64',0xaa64:'arm64'}.get(struct.unpack_from('<H',data,offset+4)[0])
    raise RuntimeError('Unknown native library format')


def verify(path):
    with zipfile.ZipFile(path) as z:
        names=z.namelist()
        if len(names)!=len(set(names)):raise RuntimeError('Duplicate archive paths')
        for name in names:
            p=Path(name)
            if p.is_absolute() or '..' in p.parts or '.git' in p.parts or '__pycache__' in p.parts or p.suffix.lower() in ('.c','.cpp','.pyx','.pdb','.map') or '.dSYM' in name:
                raise RuntimeError('Forbidden archive member: '+name)
        m=json.loads(z.read('native-manifest.json'))
        if m['python']!=CONFIG['python'] or m['abi']!='cpython-312' or set(m['modules'])!=set(CONFIG['modules']):
            raise RuntimeError('Unsupported runtime/module manifest')
        for key,source in CONFIG['modules'].items():
            entry=m['modules'][key]
            if entry['source']!=source or z.read(source).decode().replace('\r\n','\n')!=wrapper(key):
                raise RuntimeError('Original or altered protected source: '+source)
            data=z.read(entry['library'])
            if hashlib.sha256(data).hexdigest()!=entry['sha256'] or architecture(data)!=m['machine']:
                raise RuntimeError('Library checksum/architecture mismatch: '+key)
        # Require the helper generated by this archive's own checked packaging script.
        script=z.read('scripts/native_packaging.py').decode()
        expected=next(ast.literal_eval(n.value) for n in ast.parse(script).body if isinstance(n,ast.Assign)
                      and any(isinstance(t,ast.Name) and t.id=='LOADER' for t in n.targets))
        if z.read('native_loader.py').decode().replace('\r\n','\n')!=expected:
            raise RuntimeError('Altered native loader')
        runtime='python/python.exe' if m['system']=='win32' else 'python/bin/python3.12'
        for required in (runtime,'LICENSE','python-licenses/provenance.json','uv-licenses/LICENSE-MIT','docs/licenses/Cython-LICENSE.txt'):
            z.getinfo(required)
    print(path.name,m['system'],m['machine'],'content/hash/architecture OK')
    return m

if __name__=='__main__':
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('archives',nargs='+',type=Path)
    for path in ap.parse_args().archives:verify(path)
